(SAMPLES,) = glob_wildcards("resources/azaphenalenes_xyz/{sample}.xyz")


rule all:
    input:
        expand("results/{sample}.csv", sample=SAMPLES),
    output:
        "results/combined.csv",
    conda:
        "envs/coulson.yml"
    shell:
        "csvstack {input} > {output}"


rule one:
    input:
        "results/2.csv",
    output:
        "results/combined.csv",
    conda:
        "envs/coulson.yml"
    shell:
        "csvstack {input} > {output}"


rule calculate_compound:
    input:
        "resources/azaphenalenes_xyz/{sample}.xyz",
    output:
        "results/{sample}.csv",
    conda:
        "envs/coulson.yml"
    script:
        "scripts/calculate.py"
